/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PermittedContentPattern =
  | PermittedContentRequire
  | PermittedContentOptional
  | PermittedContentOneOrMore
  | PermittedContentZeroOrMore
  | PermittedContentChoice
  | PermittedContentTransparent;
export type Model = ContentType | ContentType[];
export type ContentType = string | Category;
export type Category =
  | "#text"
  | "#nonEmptyText"
  | "#phrasing"
  | "#flow"
  | "#interactive"
  | "#heading"
  | "#sectioning"
  | "#metadata"
  | "#embedded"
  | "#palpable"
  | "#script-supporting"
  | "#SVGAnimation"
  | "#SVGBasicShapes"
  | "#SVGContainer"
  | "#SVGDescriptive"
  | "#SVGFilterPrimitive"
  | "#SVGFont"
  | "#SVGGradient"
  | "#SVGGraphics"
  | "#SVGGraphicsReferencing"
  | "#SVGLightSource"
  | "#SVGNeverRendered"
  | "#SVGNone"
  | "#SVGPaintServer"
  | "#SVGRenderable"
  | "#SVGShape"
  | "#SVGStructural"
  | "#SVGStructurallyExternal"
  | "#SVGTextContent"
  | "#SVGTextContentChild"
  | "#MathMLPresentation"
  | "#MathMLScript"
  | "#MathMLTabular";

export interface ContentModelsSchema {
  __contentModel?: ContentModel;
}
export interface ContentModel {
  contents: PermittedContentPattern[] | boolean;
  descendantOf?: string;
  /**
   * Elements that this element must NOT appear as a descendant of. Each entry is a CSS selector matching forbidden ancestor elements.
   */
  forbiddenAncestors?: string[];
  /**
   * Attributes that must be unique among sibling elements of the same type. If this element has one of these attributes, no other sibling element of the same type may also have it. Example: `["default"]` for `<track>` — only one `<track>` per parent may have `default`.
   */
  uniqueAttrs?: string[];
  conditional?: {
    condition: string;
    contents: PermittedContentPattern[] | boolean;
  }[];
}
export interface PermittedContentRequire {
  require: Model | PermittedContentPattern[];
  max?: number;
  min?: number;
  _TODO_?: string;
}
export interface PermittedContentOptional {
  optional: Model | PermittedContentPattern[];
  max?: number;
  _TODO_?: string;
}
export interface PermittedContentOneOrMore {
  oneOrMore: Model | PermittedContentPattern[];
  max?: number;
  _TODO_?: string;
}
export interface PermittedContentZeroOrMore {
  zeroOrMore: Model | PermittedContentPattern[];
  max?: number;
  _TODO_?: string;
}
export interface PermittedContentChoice {
  /**
   * @minItems 2
   * @maxItems 5
   */
  choice:
    | [PermittedContentPattern[], PermittedContentPattern[]]
    | [PermittedContentPattern[], PermittedContentPattern[], PermittedContentPattern[]]
    | [PermittedContentPattern[], PermittedContentPattern[], PermittedContentPattern[], PermittedContentPattern[]]
    | [
        PermittedContentPattern[],
        PermittedContentPattern[],
        PermittedContentPattern[],
        PermittedContentPattern[],
        PermittedContentPattern[]
      ];
  _TODO_?: string;
}
export interface PermittedContentTransparent {
  transparent: string;
}
