[package]
name = "markuplint-rules"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
markuplint-core = { path = "../markuplint-core" }
markuplint-dom = { path = "../markuplint-dom" }
markuplint-selector = { path = "../markuplint-selector" }
markuplint-types = { path = "../markuplint-types" }
fancy-regex = "0.14"
regex = { workspace = true }
strsim = "0.11"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[dev-dependencies]
markuplint-dom = { path = "../markuplint-dom", features = ["html-parser"] }
markuplint-html-parser = { path = "../markuplint-html-parser" }

[lints]
workspace = true
