import { describe, test, expect } from 'vitest';

import { pugParse } from './index.js';

describe('parser', () => {
	test('basic code', () => {
		const ast = pugParse(`html(lang=en)
	head
		title Title
	body
		// HTML comment
		//- Pug comment
		<!-- HTML raw comment -->
		h1 Title
		p= variable
		p#the-id.the-class1.the-class2
			| tag #[em interpolation] and text
		img(
			src="path/to"
			alt="image"
		)
		img#the-id2(
			src="path/to"
			alt="image"
		).the-class3
		<div>
			<span>Raw HTML</span>
		</div>
		ul
			each article in articles
				li: a(href=article.href)= article.title
		if bool
			div True
		else if bool2
			div Any
		else
			div False
		case variable
			when "cond"
				- break
			when "cond2"
				p Condition 2
			when "cond3"
				p Condition 3
			default
				p Default
		script.
			console.log(123);
		.
			<script>alert(123)</script>
		:any-filter(arg1 arg2 arg3=123)
			filter contents
		div&attributes({ foo: 'bar' })
		p.
			This is a very long and boring paragraph that spans multiple lines.
			Suddenly there is a #[strong strongly worded phrase] that cannot be
			#[em ignored].
`);
		// console.log(JSON.stringify(ast));
		expect(ast).toStrictEqual({
			type: 'Block',
			line: 0,
			nodes: [
				{
					type: 'Tag',
					name: 'html',
					raw: 'html(lang=en)',
					offset: 0,
					endOffset: 13,
					line: 1,
					endLine: 1,
					column: 1,
					endColumn: 14,
					attrs: [
						{
							name: 'lang',
							val: 'en',
							mustEscape: true,
							offset: 5,
							endOffset: 12,
							line: 1,
							endLine: 1,
							column: 6,
							endColumn: 13,
							raw: 'lang=en',
						},
					],
					attributeBlocks: [],
					block: {
						type: 'Block',
						line: 1,
						nodes: [
							{
								type: 'Tag',
								name: 'head',
								raw: 'head',
								offset: 15,
								endOffset: 19,
								line: 2,
								endLine: 2,
								column: 2,
								endColumn: 6,
								attrs: [],
								attributeBlocks: [],
								block: {
									type: 'Block',
									nodes: [
										{
											type: 'Tag',
											name: 'title',
											raw: 'title',
											offset: 22,
											endOffset: 27,
											line: 3,
											endLine: 3,
											column: 3,
											endColumn: 8,
											block: {
												type: 'Block',
												nodes: [
													{
														type: 'Text',
														raw: 'Title',
														offset: 28,
														endOffset: 33,
														line: 3,
														endLine: 3,
														column: 9,
														endColumn: 14,
														val: 'Title',
														filename: null,
													},
												],
												line: 3,
											},
											attrs: [],
											attributeBlocks: [],
											filename: null,
											isInline: false,
											selfClosing: false,
										},
									],
									line: 2,
								},
								filename: null,
								isInline: false,
								selfClosing: false,
							},
							{
								type: 'Tag',
								name: 'body',
								raw: 'body',
								offset: 35,
								endOffset: 39,
								line: 4,
								endLine: 4,
								column: 2,
								endColumn: 6,
								attrs: [],
								attributeBlocks: [],
								block: {
									type: 'Block',
									line: 4,
									nodes: [
										{
											type: 'Comment',
											val: ' HTML comment',
											buffer: true,
											raw: '// HTML comment',
											offset: 42,
											endOffset: 57,
											line: 5,
											endLine: 5,
											column: 3,
											endColumn: 18,
											filename: null,
										},
										{
											type: 'Comment',
											val: ' Pug comment',
											buffer: false,
											raw: '//- Pug comment',
											offset: 60,
											endOffset: 75,
											line: 6,
											endLine: 6,
											column: 3,
											endColumn: 18,
											filename: null,
										},
										{
											type: 'Text',
											raw: '<!-- HTML raw comment -->',
											offset: 78,
											endOffset: 103,
											line: 7,
											endLine: 7,
											column: 3,
											endColumn: 28,
											val: '<!-- HTML raw comment -->',
											filename: null,
										},
										{
											type: 'Tag',
											name: 'h1',
											raw: 'h1',
											offset: 106,
											endOffset: 108,
											line: 8,
											endLine: 8,
											column: 3,
											endColumn: 5,
											block: {
												type: 'Block',
												nodes: [
													{
														type: 'Text',
														raw: 'Title',
														offset: 109,
														endOffset: 114,
														line: 8,
														endLine: 8,
														column: 6,
														endColumn: 11,
														val: 'Title',
														filename: null,
													},
												],
												line: 8,
											},
											attrs: [],
											attributeBlocks: [],
											filename: null,
											isInline: false,
											selfClosing: false,
										},
										{
											type: 'Tag',
											name: 'p',
											raw: 'p',
											offset: 117,
											endOffset: 118,
											line: 9,
											endLine: 9,
											column: 3,
											endColumn: 4,
											block: {
												type: 'Block',
												nodes: [
													{
														type: 'Code',
														raw: '= variable',
														val: 'variable',
														buffer: true,
														mustEscape: true,
														isInline: true,
														offset: 118,
														endOffset: 128,
														line: 9,
														endLine: 9,
														column: 4,
														endColumn: 14,
														block: {
															type: 'Block',
															line: 0,
															nodes: [],
														},
														filename: null,
													},
												],
												line: 9,
											},
											attrs: [],
											attributeBlocks: [],
											filename: null,
											isInline: false,
											selfClosing: false,
										},
										{
											type: 'Tag',
											name: 'p',
											raw: 'p#the-id.the-class1.the-class2',
											offset: 131,
											endOffset: 161,
											line: 10,
											endLine: 10,
											column: 3,
											endColumn: 33,
											block: {
												type: 'Block',
												nodes: [
													{
														type: 'Text',
														raw: 'tag ',
														offset: 167,
														endOffset: 171,
														line: 11,
														endLine: 11,
														column: 6,
														endColumn: 10,
														val: 'tag ',
														filename: null,
													},
													{
														type: 'Tag',
														name: 'em',
														raw: 'em',
														offset: 173,
														endOffset: 175,
														line: 11,
														endLine: 11,
														column: 12,
														endColumn: 14,
														block: {
															type: 'Block',
															nodes: [
																{
																	type: 'Text',
																	raw: 'interpolation',
																	offset: 176,
																	endOffset: 189,
																	line: 11,
																	endLine: 11,
																	column: 15,
																	endColumn: 28,
																	val: 'interpolation',
																	filename: null,
																},
															],
															line: 11,
														},
														attrs: [],
														attributeBlocks: [],
														filename: null,
														isInline: true,
														selfClosing: false,
													},
													{
														type: 'Text',
														raw: ' and text',
														offset: 190,
														endOffset: 199,
														line: 11,
														endLine: 11,
														column: 29,
														endColumn: 38,
														val: ' and text',
														filename: null,
													},
												],
												line: 10,
											},
											attrs: [
												{
													name: 'id',
													val: "'the-id'",
													mustEscape: false,
													offset: 132,
													endOffset: 139,
													line: 10,
													endLine: 10,
													column: 4,
													endColumn: 11,
													raw: '#the-id',
												},
												{
													name: 'class',
													val: "'the-class1'",
													mustEscape: false,
													offset: 139,
													endOffset: 150,
													line: 10,
													endLine: 10,
													column: 11,
													endColumn: 22,
													raw: '.the-class1',
												},
												{
													name: 'class',
													val: "'the-class2'",
													mustEscape: false,
													offset: 150,
													endOffset: 161,
													line: 10,
													endLine: 10,
													column: 22,
													endColumn: 33,
													raw: '.the-class2',
												},
											],
											attributeBlocks: [],
											filename: null,
											isInline: false,
											selfClosing: false,
										},
										{
											type: 'Tag',
											name: 'img',
											raw: 'img(\n\t\t\tsrc="path/to"\n\t\t\talt="image"\n\t\t)',
											offset: 202,
											endOffset: 242,
											line: 12,
											endLine: 15,
											column: 3,
											endColumn: 4,
											block: { type: 'Block', nodes: [], line: 12 },
											attrs: [
												{
													name: 'src',
													val: '"path/to"',
													mustEscape: true,
													offset: 210,
													endOffset: 223,
													line: 13,
													endLine: 13,
													column: 4,
													endColumn: 17,
													raw: 'src="path/to"',
												},
												{
													name: 'alt',
													val: '"image"',
													mustEscape: true,
													offset: 227,
													endOffset: 238,
													line: 14,
													endLine: 14,
													column: 4,
													endColumn: 15,
													raw: 'alt="image"',
												},
											],
											attributeBlocks: [],
											filename: null,
											isInline: true,
											selfClosing: false,
										},
										{
											type: 'Tag',
											name: 'img',
											raw: 'img#the-id2(\n\t\t\tsrc="path/to"\n\t\t\talt="image"\n\t\t).the-class3',
											offset: 245,
											endOffset: 304,
											line: 16,
											endLine: 19,
											column: 3,
											endColumn: 15,
											block: { type: 'Block', nodes: [], line: 16 },
											attrs: [
												{
													name: 'id',
													val: "'the-id2'",
													mustEscape: false,
													offset: 248,
													endOffset: 256,
													line: 16,
													endLine: 16,
													column: 6,
													endColumn: 14,
													raw: '#the-id2',
												},
												{
													name: 'src',
													val: '"path/to"',
													mustEscape: true,
													offset: 261,
													endOffset: 274,
													line: 17,
													endLine: 17,
													column: 4,
													endColumn: 17,
													raw: 'src="path/to"',
												},
												{
													name: 'alt',
													val: '"image"',
													mustEscape: true,
													offset: 278,
													endOffset: 289,
													line: 18,
													endLine: 18,
													column: 4,
													endColumn: 15,
													raw: 'alt="image"',
												},
												{
													name: 'class',
													val: "'the-class3'",
													mustEscape: false,
													offset: 293,
													endOffset: 304,
													line: 19,
													endLine: 19,
													column: 4,
													endColumn: 15,
													raw: '.the-class3',
												},
											],
											attributeBlocks: [],
											filename: null,
											isInline: true,
											selfClosing: false,
										},
										{
											type: 'Text',
											raw: '<div>\n\t\t\t<span>Raw HTML</span>\n\t\t</div>',
											offset: 307,
											endOffset: 346,
											line: 20,
											endLine: 22,
											column: 3,
											endColumn: 9,
											val: '<div>',
											filename: null,
										},
										{
											type: 'Tag',
											name: 'ul',
											raw: 'ul',
											offset: 349,
											endOffset: 351,
											line: 23,
											endLine: 23,
											column: 3,
											endColumn: 5,
											block: {
												type: 'Block',
												nodes: [
													{
														type: 'Each',
														val: 'article',
														obj: 'articles',
														key: null,
														raw: 'each article in articles',
														offset: 355,
														endOffset: 379,
														line: 24,
														endLine: 24,
														column: 4,
														endColumn: 28,
														block: {
															type: 'Block',
															nodes: [
																{
																	type: 'Tag',
																	name: 'li',
																	raw: 'li',
																	offset: 384,
																	endOffset: 386,
																	line: 25,
																	endLine: 25,
																	column: 5,
																	endColumn: 7,
																	block: {
																		type: 'Block',
																		nodes: [
																			{
																				type: 'Tag',
																				name: 'a',
																				raw: 'a(href=article.href)',
																				offset: 388,
																				endOffset: 408,
																				line: 25,
																				endLine: 25,
																				column: 9,
																				endColumn: 29,
																				block: {
																					type: 'Block',
																					nodes: [
																						{
																							type: 'Code',
																							raw: '= article.title',
																							val: 'article.title',
																							buffer: true,
																							mustEscape: true,
																							isInline: true,
																							offset: 408,
																							endOffset: 423,
																							line: 25,
																							endLine: 25,
																							column: 29,
																							endColumn: 44,
																							block: {
																								type: 'Block',
																								line: 0,
																								nodes: [],
																							},
																							filename: null,
																						},
																					],
																					line: 25,
																				},
																				attrs: [
																					{
																						name: 'href',
																						val: 'article.href',
																						mustEscape: true,
																						offset: 390,
																						endOffset: 407,
																						line: 25,
																						endLine: 25,
																						column: 11,
																						endColumn: 28,
																						raw: 'href=article.href',
																					},
																				],
																				attributeBlocks: [],
																				filename: null,
																				isInline: true,
																				selfClosing: false,
																			},
																		],
																		line: 25,
																	},
																	attrs: [],
																	attributeBlocks: [],
																	filename: null,
																	isInline: false,
																	selfClosing: false,
																},
															],
															line: 25,
														},
														filename: null,
													},
												],
												line: 23,
											},
											attrs: [],
											attributeBlocks: [],
											filename: null,
											isInline: false,
											selfClosing: false,
										},
										{
											type: 'Conditional',
											raw: 'if bool',
											test: 'bool',
											offset: 426,
											endOffset: 433,
											line: 26,
											endLine: 26,
											column: 3,
											endColumn: 10,
											block: {
												type: 'Block',
												nodes: [
													{
														type: 'Tag',
														name: 'div',
														raw: 'div',
														offset: 437,
														endOffset: 440,
														line: 27,
														endLine: 27,
														column: 4,
														endColumn: 7,
														block: {
															type: 'Block',
															nodes: [
																{
																	type: 'Text',
																	raw: 'True',
																	offset: 441,
																	endOffset: 445,
																	line: 27,
																	endLine: 27,
																	column: 8,
																	endColumn: 12,
																	val: 'True',
																	filename: null,
																},
															],
															line: 27,
														},
														attrs: [],
														attributeBlocks: [],
														filename: null,
														isInline: false,
														selfClosing: false,
													},
												],
												line: 27,
											},
											filename: null,
										},
										{
											type: 'Conditional',
											raw: 'else if bool2',
											test: 'bool2',
											offset: 448,
											endOffset: 461,
											line: 28,
											endLine: 28,
											column: 3,
											endColumn: 16,
											block: {
												type: 'Block',
												nodes: [
													{
														type: 'Tag',
														name: 'div',
														raw: 'div',
														offset: 465,
														endOffset: 468,
														line: 29,
														endLine: 29,
														column: 4,
														endColumn: 7,
														block: {
															type: 'Block',
															nodes: [
																{
																	type: 'Text',
																	raw: 'Any',
																	offset: 469,
																	endOffset: 472,
																	line: 29,
																	endLine: 29,
																	column: 8,
																	endColumn: 11,
																	val: 'Any',
																	filename: null,
																},
															],
															line: 29,
														},
														attrs: [],
														attributeBlocks: [],
														filename: null,
														isInline: false,
														selfClosing: false,
													},
												],
												line: 29,
											},
											filename: null,
										},
										{
											type: 'Conditional',
											raw: 'else',
											test: 'bool2',
											offset: 475,
											endOffset: 479,
											line: 30,
											endLine: 30,
											column: 3,
											endColumn: 7,
											block: {
												type: 'Block',
												nodes: [
													{
														type: 'Tag',
														name: 'div',
														raw: 'div',
														offset: 483,
														endOffset: 486,
														line: 31,
														endLine: 31,
														column: 4,
														endColumn: 7,
														block: {
															type: 'Block',
															nodes: [
																{
																	type: 'Text',
																	raw: 'False',
																	offset: 487,
																	endOffset: 492,
																	line: 31,
																	endLine: 31,
																	column: 8,
																	endColumn: 13,
																	val: 'False',
																	filename: null,
																},
															],
															line: 31,
														},
														attrs: [],
														attributeBlocks: [],
														filename: null,
														isInline: false,
														selfClosing: false,
													},
												],
												line: 31,
											},
											filename: null,
										},
										{
											type: 'Case',
											expr: 'variable',
											raw: 'case variable',
											offset: 495,
											endOffset: 508,
											line: 32,
											endLine: 32,
											column: 3,
											endColumn: 16,
											block: {
												type: 'Block',
												nodes: [
													{
														type: 'When',
														expr: '"cond"',
														raw: 'when "cond"',
														offset: 512,
														endOffset: 523,
														line: 33,
														endLine: 33,
														column: 4,
														endColumn: 15,
														block: {
															type: 'Block',
															nodes: [
																{
																	type: 'Code',
																	raw: '- break',
																	val: 'break',
																	buffer: false,
																	mustEscape: false,
																	isInline: false,
																	offset: 528,
																	endOffset: 535,
																	line: 34,
																	endLine: 34,
																	column: 5,
																	endColumn: 12,
																	block: {
																		type: 'Block',
																		line: 0,
																		nodes: [],
																	},
																	filename: null,
																},
															],
															line: 34,
														},
														filename: null,
													},
													{
														type: 'When',
														expr: '"cond2"',
														raw: 'when "cond2"',
														offset: 539,
														endOffset: 551,
														line: 35,
														endLine: 35,
														column: 4,
														endColumn: 16,
														block: {
															type: 'Block',
															nodes: [
																{
																	type: 'Tag',
																	name: 'p',
																	raw: 'p',
																	offset: 556,
																	endOffset: 557,
																	line: 36,
																	endLine: 36,
																	column: 5,
																	endColumn: 6,
																	block: {
																		type: 'Block',
																		nodes: [
																			{
																				type: 'Text',
																				raw: 'Condition 2',
																				offset: 558,
																				endOffset: 569,
																				line: 36,
																				endLine: 36,
																				column: 7,
																				endColumn: 18,
																				val: 'Condition 2',
																				filename: null,
																			},
																		],
																		line: 36,
																	},
																	attrs: [],
																	attributeBlocks: [],
																	filename: null,
																	isInline: false,
																	selfClosing: false,
																},
															],
															line: 36,
														},
														filename: null,
													},
													{
														type: 'When',
														expr: '"cond3"',
														raw: 'when "cond3"',
														offset: 573,
														endOffset: 585,
														line: 37,
														endLine: 37,
														column: 4,
														endColumn: 16,
														block: {
															type: 'Block',
															nodes: [
																{
																	type: 'Tag',
																	name: 'p',
																	raw: 'p',
																	offset: 590,
																	endOffset: 591,
																	line: 38,
																	endLine: 38,
																	column: 5,
																	endColumn: 6,
																	block: {
																		type: 'Block',
																		nodes: [
																			{
																				type: 'Text',
																				raw: 'Condition 3',
																				offset: 592,
																				endOffset: 603,
																				line: 38,
																				endLine: 38,
																				column: 7,
																				endColumn: 18,
																				val: 'Condition 3',
																				filename: null,
																			},
																		],
																		line: 38,
																	},
																	attrs: [],
																	attributeBlocks: [],
																	filename: null,
																	isInline: false,
																	selfClosing: false,
																},
															],
															line: 38,
														},
														filename: null,
													},
													{
														type: 'When',
														expr: 'default',
														raw: 'default',
														offset: 607,
														endOffset: 614,
														line: 39,
														endLine: 39,
														column: 4,
														endColumn: 11,
														block: {
															type: 'Block',
															nodes: [
																{
																	type: 'Tag',
																	name: 'p',
																	raw: 'p',
																	offset: 619,
																	endOffset: 620,
																	line: 40,
																	endLine: 40,
																	column: 5,
																	endColumn: 6,
																	block: {
																		type: 'Block',
																		nodes: [
																			{
																				type: 'Text',
																				raw: 'Default',
																				offset: 621,
																				endOffset: 628,
																				line: 40,
																				endLine: 40,
																				column: 7,
																				endColumn: 14,
																				val: 'Default',
																				filename: null,
																			},
																		],
																		line: 40,
																	},
																	attrs: [],
																	attributeBlocks: [],
																	filename: null,
																	isInline: false,
																	selfClosing: false,
																},
															],
															line: 40,
														},
														filename: null,
													},
												],
												line: 33,
											},
											filename: null,
										},
										{
											type: 'Tag',
											name: 'script',
											raw: 'script',
											offset: 631,
											endOffset: 637,
											line: 41,
											endLine: 41,
											column: 3,
											endColumn: 9,
											block: {
												type: 'Block',
												nodes: [
													{
														type: 'Text',
														raw: 'console.log(123);',
														offset: 642,
														endOffset: 659,
														line: 42,
														endLine: 42,
														column: 4,
														endColumn: 21,
														val: 'console.log(123);',
														filename: null,
													},
												],
												line: 41,
											},
											attrs: [],
											attributeBlocks: [],
											filename: null,
											isInline: false,
											selfClosing: false,
										},
										{
											type: 'Text',
											raw: '<script>alert(123)</script>',
											offset: 667,
											endOffset: 694,
											line: 44,
											endLine: 44,
											column: 4,
											endColumn: 31,
											val: '<script>alert(123)</script>',
											filename: null,
										},
										{
											type: 'Filter',
											name: 'any-filter',
											raw: ':any-filter(arg1 arg2 arg3=123)',
											offset: 697,
											endOffset: 728,
											line: 45,
											endLine: 45,
											column: 3,
											endColumn: 34,
											block: {
												type: 'Block',
												nodes: [
													{
														type: 'Text',
														raw: 'filter contents',
														offset: 732,
														endOffset: 747,
														line: 46,
														endLine: 46,
														column: 4,
														endColumn: 19,
														val: 'filter contents',
														filename: null,
													},
												],
												line: 45,
											},
											attrs: [
												{
													name: 'arg1',
													val: true,
													mustEscape: true,
													offset: 709,
													endOffset: 713,
													line: 45,
													endLine: 45,
													column: 15,
													endColumn: 19,
													raw: 'arg1',
												},
												{
													name: 'arg2',
													val: true,
													mustEscape: true,
													offset: 714,
													endOffset: 718,
													line: 45,
													endLine: 45,
													column: 20,
													endColumn: 24,
													raw: 'arg2',
												},
												{
													name: 'arg3',
													val: '123',
													mustEscape: true,
													offset: 719,
													endOffset: 727,
													line: 45,
													endLine: 45,
													column: 25,
													endColumn: 33,
													raw: 'arg3=123',
												},
											],
											filename: null,
										},
										{
											attributeBlocks: [
												{
													column: 6,
													line: 47,
													type: 'AttributeBlock',
													val: "{ foo: 'bar' }",
												},
											],
											attrs: [],
											block: {
												line: 47,
												nodes: [],
												type: 'Block',
											},
											column: 3,
											endColumn: 6,
											endLine: 47,
											endOffset: 753,
											line: 47,
											name: 'div',
											offset: 750,
											raw: 'div',
											type: 'Tag',
											filename: null,
											isInline: false,
											selfClosing: false,
										},
										{
											attributeBlocks: [],
											attrs: [],
											block: {
												line: 48,
												nodes: [
													{
														type: 'Text',
														raw: '\n\t\t\tThis is a very long and boring paragraph that spans multiple lines.\n\t\t\tSuddenly there is a #[strong strongly worded phrase] that cannot be\n\t\t\t#[em ignored].',
														column: 5,
														endColumn: 18,
														endLine: 51,
														endOffset: 945,
														line: 48,
														offset: 785,
														val: 'This is a very long and boring paragraph that spans multiple lines.',
													},
													{
														type: 'Tag',
														raw: 'strong',
														name: 'strong',
														column: 26,
														endColumn: 32,
														endLine: 50,
														endOffset: 888,
														line: 50,
														offset: 882,
														attributeBlocks: [],
														attrs: [],
														block: {
															line: 50,
															nodes: [
																{
																	column: 5,
																	endColumn: 18,
																	endLine: 51,
																	endOffset: 945,
																	line: 48,
																	offset: 785,
																	raw: '\n\t\t\tThis is a very long and boring paragraph that spans multiple lines.\n\t\t\tSuddenly there is a #[strong strongly worded phrase] that cannot be\n\t\t\t#[em ignored].',
																	type: 'Text',
																	val: 'strongly worded phrase',
																},
															],
															type: 'Block',
														},
														filename: null,
														isInline: true,
														selfClosing: false,
													},
													{
														type: 'Text',
														raw: '\n\t\t\tThis is a very long and boring paragraph that spans multiple lines.\n\t\t\tSuddenly there is a #[strong strongly worded phrase] that cannot be\n\t\t\t#[em ignored].',
														column: 5,
														endColumn: 18,
														endLine: 51,
														endOffset: 945,
														line: 48,
														offset: 785,
														val: ' that cannot be',
													},
													{
														type: 'Tag',
														name: 'em',
														raw: 'em',
														column: 6,
														endColumn: 8,
														endLine: 51,
														endOffset: 935,
														line: 51,
														offset: 933,
														attributeBlocks: [],
														attrs: [],
														block: {
															line: 51,
															nodes: [
																{
																	column: 9,
																	endColumn: 16,
																	endLine: 51,
																	endOffset: 943,
																	line: 51,
																	offset: 936,
																	raw: 'ignored',
																	type: 'Text',
																	val: 'ignored',
																	filename: null,
																},
															],
															type: 'Block',
														},
														isInline: true,
														selfClosing: false,
														filename: null,
													},
													{
														type: 'Text',
														raw: '.',
														column: 17,
														endColumn: 18,
														endLine: 51,
														endOffset: 945,
														line: 51,
														offset: 944,
														val: '.',
														filename: null,
													},
												],
												type: 'Block',
											},
											column: 3,
											endColumn: 4,
											endLine: 48,
											endOffset: 784,
											line: 48,
											name: 'p',
											offset: 783,
											raw: 'p',
											type: 'Tag',
											filename: null,
											isInline: false,
											selfClosing: false,
										},
									],
								},
								filename: null,
								isInline: false,
								selfClosing: false,
							},
						],
					},
					filename: null,
					isInline: false,
					selfClosing: false,
				},
			],
		});
	});

	/**
	 * @see https://pugjs.org/language/mixins.html
	 */
	test('use mixin', () => {
		const ast = pugParse(`//- Declaration
mixin list
	ul
		li foo
		li bar
		li baz
//- Use
+list
+list

mixin article(title)
	.article
		.article-wrapper
			h1= title
			if block
				block
			else
				p No content provided

+article('Hello world')

+article('Hello world')
	p This is my
	p Amazing article

mixin link(href, name)
	//- attributes == {class: "btn"}
	a(class!=attributes.class href=href)= name

+link('/foo', 'foo')(class="btn")
`);
		// console.log(JSON.stringify(ast));
		expect(ast).toStrictEqual({
			type: 'Block',
			nodes: [
				{
					type: 'Comment',
					val: ' Declaration',
					buffer: false,
					raw: '//- Declaration',
					offset: 0,
					endOffset: 15,
					line: 1,
					endLine: 1,
					column: 1,
					endColumn: 16,
					filename: null,
				},
				{
					type: 'Mixin',
					name: 'list',
					args: null,
					call: false,
					raw: 'mixin list',
					offset: 16,
					endOffset: 26,
					line: 2,
					endLine: 2,
					column: 1,
					endColumn: 11,
					block: {
						type: 'Block',
						nodes: [
							{
								type: 'Tag',
								name: 'ul',
								raw: 'ul',
								offset: 28,
								endOffset: 30,
								line: 3,
								endLine: 3,
								column: 2,
								endColumn: 4,
								block: {
									type: 'Block',
									nodes: [
										{
											type: 'Tag',
											name: 'li',
											raw: 'li',
											offset: 33,
											endOffset: 35,
											line: 4,
											endLine: 4,
											column: 3,
											endColumn: 5,
											block: {
												type: 'Block',
												nodes: [
													{
														type: 'Text',
														raw: 'foo',
														offset: 36,
														endOffset: 39,
														line: 4,
														endLine: 4,
														column: 6,
														endColumn: 9,
														val: 'foo',
														filename: null,
													},
												],
												line: 4,
											},
											attrs: [],
											attributeBlocks: [],
											isInline: false,
											selfClosing: false,
											filename: null,
										},
										{
											type: 'Tag',
											name: 'li',
											raw: 'li',
											offset: 42,
											endOffset: 44,
											line: 5,
											endLine: 5,
											column: 3,
											endColumn: 5,
											block: {
												type: 'Block',
												nodes: [
													{
														type: 'Text',
														raw: 'bar',
														offset: 45,
														endOffset: 48,
														line: 5,
														endLine: 5,
														column: 6,
														endColumn: 9,
														val: 'bar',
														filename: null,
													},
												],
												line: 5,
											},
											attrs: [],
											attributeBlocks: [],
											isInline: false,
											selfClosing: false,
											filename: null,
										},
										{
											type: 'Tag',
											name: 'li',
											raw: 'li',
											offset: 51,
											endOffset: 53,
											line: 6,
											endLine: 6,
											column: 3,
											endColumn: 5,
											block: {
												type: 'Block',
												nodes: [
													{
														type: 'Text',
														raw: 'baz',
														offset: 54,
														endOffset: 57,
														line: 6,
														endLine: 6,
														column: 6,
														endColumn: 9,
														val: 'baz',
														filename: null,
													},
												],
												line: 6,
											},
											attrs: [],
											attributeBlocks: [],
											isInline: false,
											selfClosing: false,
											filename: null,
										},
									],
									line: 3,
								},
								attrs: [],
								attributeBlocks: [],
								isInline: false,
								selfClosing: false,
								filename: null,
							},
						],
						line: 3,
					},
					attrs: [],
					attributeBlocks: [],
					filename: null,
				},
				{
					type: 'Comment',
					val: ' Use',
					buffer: false,
					raw: '',
					offset: 58,
					endOffset: 58,
					line: 7,
					endLine: 7,
					column: 1,
					endColumn: 1,
					filename: null,
				},
				{
					type: 'Mixin',
					name: 'list',
					args: null,
					call: true,
					raw: '+list',
					offset: 66,
					endOffset: 71,
					line: 8,
					endLine: 8,
					column: 1,
					endColumn: 6,
					block: null,
					attrs: [],
					attributeBlocks: [],
					filename: null,
				},
				{
					type: 'Mixin',
					name: 'list',
					args: null,
					call: true,
					raw: '+list',
					offset: 72,
					endOffset: 77,
					line: 9,
					endLine: 9,
					column: 1,
					endColumn: 6,
					block: null,
					attrs: [],
					attributeBlocks: [],
					filename: null,
				},
				{
					type: 'Mixin',
					name: 'article',
					args: 'title',
					call: false,
					raw: 'mixin article(title)',
					offset: 79,
					endOffset: 99,
					line: 11,
					endLine: 11,
					column: 1,
					endColumn: 21,
					block: {
						type: 'Block',
						nodes: [
							{
								type: 'Tag',
								name: 'div',
								raw: '.article',
								offset: 101,
								endOffset: 109,
								line: 12,
								endLine: 12,
								column: 2,
								endColumn: 10,
								block: {
									type: 'Block',
									nodes: [
										{
											type: 'Tag',
											name: 'div',
											raw: '.article-wrapper',
											offset: 112,
											endOffset: 128,
											line: 13,
											endLine: 13,
											column: 3,
											endColumn: 19,
											block: {
												type: 'Block',
												nodes: [
													{
														type: 'Tag',
														name: 'h1',
														raw: 'h1',
														offset: 132,
														endOffset: 134,
														line: 14,
														endLine: 14,
														column: 4,
														endColumn: 6,
														block: {
															type: 'Block',
															nodes: [
																{
																	type: 'Code',
																	raw: '= title',
																	val: 'title',
																	buffer: true,
																	mustEscape: true,
																	isInline: true,
																	offset: 134,
																	endOffset: 141,
																	line: 14,
																	endLine: 14,
																	column: 6,
																	endColumn: 13,
																	block: {
																		type: 'Block',
																		line: 0,
																		nodes: [],
																	},
																	filename: null,
																},
															],
															line: 14,
														},
														attrs: [],
														attributeBlocks: [],
														isInline: false,
														selfClosing: false,
														filename: null,
													},
													{
														type: 'Conditional',
														raw: 'if block',
														test: 'block',
														offset: 145,
														endOffset: 153,
														line: 15,
														endLine: 15,
														column: 4,
														endColumn: 12,
														block: {
															type: 'Block',
															nodes: [
																{
																	type: 'MixinBlock',
																	raw: 'block',
																	offset: 158,
																	endOffset: 163,
																	line: 16,
																	endLine: 16,
																	column: 5,
																	endColumn: 10,
																	filename: null,
																},
															],
															line: 16,
														},
														filename: null,
													},
													{
														type: 'Conditional',
														raw: 'else',
														test: 'block',
														offset: 167,
														endOffset: 171,
														line: 17,
														endLine: 17,
														column: 4,
														endColumn: 8,
														block: {
															type: 'Block',
															nodes: [
																{
																	type: 'Tag',
																	name: 'p',
																	raw: 'p',
																	offset: 176,
																	endOffset: 177,
																	line: 18,
																	endLine: 18,
																	column: 5,
																	endColumn: 6,
																	block: {
																		type: 'Block',
																		nodes: [
																			{
																				type: 'Text',
																				raw: 'No content provided',
																				offset: 178,
																				endOffset: 197,
																				line: 18,
																				endLine: 18,
																				column: 7,
																				endColumn: 26,
																				val: 'No content provided',
																				filename: null,
																			},
																		],
																		line: 18,
																	},
																	attrs: [],
																	attributeBlocks: [],
																	isInline: false,
																	selfClosing: false,
																	filename: null,
																},
															],
															line: 18,
														},
														filename: null,
													},
												],
												line: 13,
											},
											attrs: [
												{
													name: 'class',
													val: "'article-wrapper'",
													mustEscape: false,
													offset: 112,
													endOffset: 128,
													line: 13,
													endLine: 13,
													column: 3,
													endColumn: 19,
													raw: '.article-wrapper',
												},
											],
											attributeBlocks: [],
											isInline: false,
											selfClosing: false,
											filename: null,
										},
									],
									line: 12,
								},
								attrs: [
									{
										name: 'class',
										val: "'article'",
										mustEscape: false,
										offset: 101,
										endOffset: 109,
										line: 12,
										endLine: 12,
										column: 2,
										endColumn: 10,
										raw: '.article',
									},
								],
								attributeBlocks: [],
								isInline: false,
								selfClosing: false,
								filename: null,
							},
						],
						line: 12,
					},
					attrs: [],
					attributeBlocks: [],
					filename: null,
				},
				{
					type: 'Mixin',
					name: 'article',
					args: "'Hello world'",
					call: true,
					raw: "+article('Hello world')",
					offset: 199,
					endOffset: 222,
					line: 20,
					endLine: 20,
					column: 1,
					endColumn: 24,
					block: null,
					attrs: [],
					attributeBlocks: [],
					filename: null,
				},
				{
					type: 'Mixin',
					name: 'article',
					args: "'Hello world'",
					call: true,
					raw: "+article('Hello world')",
					offset: 224,
					endOffset: 247,
					line: 22,
					endLine: 22,
					column: 1,
					endColumn: 24,
					block: {
						type: 'Block',
						nodes: [
							{
								type: 'Tag',
								name: 'p',
								raw: 'p',
								offset: 249,
								endOffset: 250,
								line: 23,
								endLine: 23,
								column: 2,
								endColumn: 3,
								block: {
									type: 'Block',
									nodes: [
										{
											type: 'Text',
											raw: 'This is my',
											offset: 251,
											endOffset: 261,
											line: 23,
											endLine: 23,
											column: 4,
											endColumn: 14,
											val: 'This is my',
											filename: null,
										},
									],
									line: 23,
								},
								attrs: [],
								attributeBlocks: [],
								isInline: false,
								selfClosing: false,
								filename: null,
							},
							{
								type: 'Tag',
								name: 'p',
								raw: 'p',
								offset: 263,
								endOffset: 264,
								line: 24,
								endLine: 24,
								column: 2,
								endColumn: 3,
								block: {
									type: 'Block',
									nodes: [
										{
											type: 'Text',
											raw: 'Amazing article',
											offset: 265,
											endOffset: 280,
											line: 24,
											endLine: 24,
											column: 4,
											endColumn: 19,
											val: 'Amazing article',
											filename: null,
										},
									],
									line: 24,
								},
								attrs: [],
								attributeBlocks: [],
								isInline: false,
								selfClosing: false,
								filename: null,
							},
						],
						line: 22,
					},
					attrs: [],
					attributeBlocks: [],
					filename: null,
				},
				{
					type: 'Mixin',
					name: 'link',
					args: 'href, name',
					call: false,
					raw: 'mixin link(href, name)',
					offset: 282,
					endOffset: 304,
					line: 26,
					endLine: 26,
					column: 1,
					endColumn: 23,
					block: {
						type: 'Block',
						nodes: [
							{
								type: 'Comment',
								val: ' attributes == {class: "btn"}',
								buffer: false,
								raw: '//- attributes == {class: "btn"}',
								offset: 306,
								endOffset: 338,
								line: 27,
								endLine: 27,
								column: 2,
								endColumn: 34,
								filename: null,
							},
							{
								type: 'Tag',
								name: 'a',
								raw: 'a(class!=attributes.class href=href)',
								offset: 340,
								endOffset: 376,
								line: 28,
								endLine: 28,
								column: 2,
								endColumn: 38,
								block: {
									type: 'Block',
									nodes: [
										{
											type: 'Code',
											raw: '= name',
											val: 'name',
											buffer: true,
											mustEscape: true,
											isInline: true,
											offset: 376,
											endOffset: 382,
											line: 28,
											endLine: 28,
											column: 38,
											endColumn: 44,
											block: {
												type: 'Block',
												nodes: [],
												line: 0,
											},
											filename: null,
										},
									],
									line: 28,
								},
								attrs: [
									{
										name: 'class',
										val: 'attributes.class',
										mustEscape: false,
										offset: 342,
										endOffset: 365,
										line: 28,
										endLine: 28,
										column: 4,
										endColumn: 27,
										raw: 'class!=attributes.class',
									},
									{
										name: 'href',
										val: 'href',
										mustEscape: true,
										offset: 366,
										endOffset: 375,
										line: 28,
										endLine: 28,
										column: 28,
										endColumn: 37,
										raw: 'href=href',
									},
								],
								attributeBlocks: [],
								isInline: true,
								selfClosing: false,
								filename: null,
							},
						],
						line: 27,
					},
					attrs: [],
					attributeBlocks: [],
					filename: null,
				},
				{
					type: 'Mixin',
					name: 'link',
					args: "'/foo', 'foo'",
					call: true,
					raw: "+link('/foo', 'foo')",
					offset: 384,
					endOffset: 404,
					line: 30,
					endLine: 30,
					column: 1,
					endColumn: 21,
					block: null,
					attrs: [],
					attributeBlocks: [],
					filename: null,
				},
			],
			line: 0,
		});
	});

	test('use mixin', () => {
		const ast = pugParse(`div
	<span>
		<img src="path/to">
	</span>
`);
		// console.log(JSON.stringify(ast));
		expect(ast).toStrictEqual({
			type: 'Block',
			nodes: [
				{
					type: 'Tag',
					name: 'div',
					raw: 'div',
					offset: 0,
					endOffset: 3,
					line: 1,
					endLine: 1,
					column: 1,
					endColumn: 4,
					block: {
						type: 'Block',
						nodes: [
							{
								type: 'Text',
								raw: '<span>\n\t\t<img src="path/to">\n\t</span>',
								offset: 5,
								endOffset: 42,
								line: 2,
								endLine: 4,
								column: 2,
								endColumn: 9,
								val: '<span>',
								filename: null,
							},
						],
						line: 1,
					},
					attrs: [],
					attributeBlocks: [],
					isInline: false,
					selfClosing: false,
					filename: null,
				},
			],
			line: 0,
		});
	});

	test('tag interpolation (Issue #58)', () => {
		const ast = pugParse(`p
	| lorem #[span ipsum]`);
		expect(ast).toStrictEqual({
			type: 'Block',
			nodes: [
				{
					type: 'Tag',
					name: 'p',
					raw: 'p',
					offset: 0,
					endOffset: 1,
					line: 1,
					endLine: 1,
					column: 1,
					endColumn: 2,
					block: {
						type: 'Block',
						nodes: [
							{
								type: 'Text',
								raw: 'lorem ',
								offset: 5,
								endOffset: 11,
								line: 2,
								endLine: 2,
								column: 4,
								endColumn: 10,
								val: 'lorem ',
								filename: null,
							},
							{
								type: 'Tag',
								name: 'span',
								raw: 'span',
								offset: 13,
								endOffset: 17,
								line: 2,
								endLine: 2,
								column: 12,
								endColumn: 16,
								block: {
									type: 'Block',
									nodes: [
										{
											type: 'Text',
											raw: 'ipsum',
											offset: 18,
											endOffset: 23,
											line: 2,
											endLine: 2,
											column: 17,
											endColumn: 22,
											val: 'ipsum',
											filename: null,
										},
									],
									line: 2,
								},
								attrs: [],
								attributeBlocks: [],
								isInline: true,
								selfClosing: false,
								filename: null,
							},
						],
						line: 1,
					},
					attrs: [],
					attributeBlocks: [],
					isInline: false,
					selfClosing: false,
					filename: null,
				},
			],
			line: 0,
		});
	});

	test('block-in-tag', () => {
		const ast = pugParse(`div.
	#text
	<img tag>
	<span>
		#text2
	</span>`);
		// console.log(JSON.stringify(ast));
		expect(ast).toStrictEqual({
			type: 'Block',
			nodes: [
				{
					type: 'Tag',
					name: 'div',
					raw: 'div',
					offset: 0,
					endOffset: 3,
					line: 1,
					endLine: 1,
					column: 1,
					endColumn: 4,
					block: {
						type: 'Block',
						nodes: [
							{
								type: 'Text',
								raw: '\n\t#text\n\t<img tag>\n\t<span>\n\t\t#text2\n\t</span>',
								offset: 4,
								endOffset: 48,
								line: 1,
								endLine: 6,
								column: 5,
								endColumn: 9,
								val: '#text',
							},
						],
						line: 1,
					},
					attrs: [],
					attributeBlocks: [],
					isInline: false,
					selfClosing: false,
					filename: null,
				},
			],
			line: 0,
		});
	});

	test('block-in-tag', () => {
		const ast = pugParse(`div.
	<input invalid-attr/>
	<input invalid-attr/>`);
		// console.log(JSON.stringify(ast));
		expect(ast).toStrictEqual({
			type: 'Block',
			nodes: [
				{
					type: 'Tag',
					name: 'div',
					raw: 'div',
					offset: 0,
					endOffset: 3,
					line: 1,
					endLine: 1,
					column: 1,
					endColumn: 4,
					block: {
						type: 'Block',
						nodes: [
							{
								type: 'Text',
								raw: '\n\t<input invalid-attr/>\n\t<input invalid-attr/>',
								offset: 4,
								endOffset: 50,
								line: 1,
								endLine: 3,
								column: 5,
								endColumn: 23,
								val: '<input invalid-attr/>',
							},
						],
						line: 1,
					},
					attrs: [],
					attributeBlocks: [],
					isInline: false,
					selfClosing: false,
					filename: null,
				},
			],
			line: 0,
		});
	});

	test('RawInclude', () => {
		const ast = pugParse(`div
	include ./path/to/image.svg`);
		expect(ast).toStrictEqual({
			type: 'Block',
			nodes: [
				{
					type: 'Tag',
					name: 'div',
					raw: 'div',
					offset: 0,
					endOffset: 3,
					line: 1,
					endLine: 1,
					column: 1,
					endColumn: 4,
					block: {
						type: 'Block',
						nodes: [
							{
								type: 'RawInclude',
								column: 2,
								endColumn: 9,
								endLine: 2,
								endOffset: 12,
								line: 2,
								offset: 5,
								raw: 'include',
								file: {
									type: 'FileReference',
									path: './path/to/image.svg',
									line: 2,
									column: 10,
								},
								filters: [],
								filename: null,
							},
						],
						line: 1,
					},
					attrs: [],
					attributeBlocks: [],
					isInline: false,
					selfClosing: false,
					filename: null,
				},
			],
			line: 0,
		});
	});

	test('BlockComment', () => {
		const ast = pugParse(`//- div
	span
	span`);
		expect(ast).toStrictEqual({
			type: 'Block',
			nodes: [
				{
					type: 'BlockComment',
					val: ' div',
					raw: '//- div',
					block: {
						type: 'Block',
						nodes: [
							{
								type: 'Text',
								raw: '\n\tspan\n\tspan',
								column: 8,
								endColumn: 6,
								endLine: 3,
								endOffset: 19,
								line: 1,
								offset: 7,
								val: 'span',
							},
						],
						line: 1,
					},
					buffer: false,
					column: 1,
					endColumn: 8,
					endLine: 1,
					endOffset: 7,
					line: 1,
					offset: 0,
					filename: null,
				},
			],
			line: 0,
		});
	});
});

describe('Issues', () => {
	test('#2110', () => {
		const ast = pugParse(`mixin foo
	if bar
		<n1>
	else
		<n2>
	<n3>
	<n4>
	<n5>
	<n5>
	<n6>`);
		expect(ast).toStrictEqual({
			type: 'Block',
			line: 0,
			nodes: [
				{
					type: 'Mixin',
					raw: 'mixin foo',
					args: null,
					attrs: [],
					attributeBlocks: [],
					call: false,
					column: 1,
					endColumn: 10,
					endLine: 1,
					endOffset: 9,
					line: 1,
					name: 'foo',
					offset: 0,
					filename: null,
					block: {
						type: 'Block',
						line: 2,
						nodes: [
							{
								type: 'Conditional',
								column: 2,
								endColumn: 8,
								endLine: 2,
								endOffset: 17,
								line: 2,
								offset: 11,
								raw: 'if bar',
								test: 'bar',
								filename: null,
								block: {
									type: 'Block',
									line: 3,
									nodes: [
										{
											type: 'Text',
											column: 3,
											endColumn: 7,
											endLine: 3,
											endOffset: 24,
											line: 3,
											offset: 20,
											raw: '<n1>',
											val: '<n1>',
											filename: null,
										},
									],
								},
							},
							{
								type: 'Conditional',
								column: 2,
								endColumn: 6,
								endLine: 4,
								endOffset: 30,
								line: 4,
								offset: 26,
								raw: 'else',
								test: 'bar',
								filename: null,
								block: {
									type: 'Block',
									line: 5,
									nodes: [
										{
											type: 'Text',
											column: 3,
											endColumn: 7,
											endLine: 5,
											endOffset: 37,
											line: 5,
											offset: 33,
											raw: '<n2>',
											val: '<n2>',
											filename: null,
										},
									],
								},
							},
							{
								type: 'Text',
								column: 2,
								endColumn: 6,
								endLine: 10,
								endOffset: 67,
								line: 6,
								offset: 39,
								raw: '<n3>\n\t<n4>\n\t<n5>\n\t<n5>\n\t<n6>',
								val: '<n3>',
								filename: null,
							},
						],
					},
				},
			],
		});
	});
});
