/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A DOM tree built from an MLAST JSON string.
 *
 * Use the constructor to parse MLAST JSON and build the DOM.
 * Then query nodes by UUID or traverse the tree.
 */
export declare class NapiDom {
  /**
   * Build a DOM from an MLAST JSON string.
   *
   * # Errors
   *
   * Returns an error if the JSON cannot be parsed as a valid MLAST document.
   */
  constructor(mlastJson: string)
  /**
   * Build a DOM by parsing an HTML string directly (no MLAST JSON).
   *
   * Uses the Rust WHATWG-conformant HTML parser. Automatically detects
   * whether the input is a full document or a fragment.
   */
  static fromHtml(html: string): NapiDom
  /** Total number of nodes in the DOM. */
  get nodeCount(): number
  /** Get a node by its UUID string. Returns null if not found. */
  getNodeByUuid(uuid: string): NapiNode | null
  /** Get a node by its internal ID. Returns null if not found. */
  getNode(id: number): NapiNode | null
  /** Get all element nodes in the DOM. */
  getElements(): Array<NapiElement>
  /** Get the children of a node by its ID. */
  getChildren(id: number): Array<NapiNode>
  /** Get the parent of a node by its ID. Returns null if root. */
  getParent(id: number): NapiNode | null
  /** Get the next sibling of a node. Returns null if last child. */
  getNextSibling(id: number): NapiNode | null
  /** Get the previous sibling of a node. Returns null if first child. */
  getPrevSibling(id: number): NapiNode | null
  /** Get all ancestor nodes of a node (bottom-up, excluding the node itself). */
  getAncestors(id: number): Array<NapiNode>
  /** Get all descendant nodes of a node in document order. */
  getDescendants(id: number): Array<NapiNode>
}

/** Result of a CSS value match attempt. */
export interface CssMatchResult {
  /** Whether the value matched the syntax. */
  matched: boolean
  /** Byte offset of the mismatch (only present when matched is false). */
  offset?: number
  /** Length of the mismatched segment (only present when matched is false). */
  length?: number
  /** Expected values at the mismatch point. */
  expected?: Array<string>
}

/** Checks whether a string is a valid floating-point number. */
export declare function isFloat(value: string): boolean

/** Checks whether a string is a valid signed integer. */
export declare function isInt(value: string): boolean

/** Checks whether a string is a valid non-zero unsigned integer. */
export declare function isNonZeroUint(value: string): boolean

/** Checks whether a string is a valid number with one of the allowed unit suffixes. */
export declare function isQuantity(value: string, units: Array<string>, numberType?: string | undefined | null): boolean

/**
 * Checks whether a string is a valid non-negative integer.
 * Optionally requires the value to be greater than `gt`.
 */
export declare function isUint(value: string, gt?: number | undefined | null): boolean

/**
 * Match a CSS property value, including CSS-wide keywords.
 *
 * Checks CSS-wide keywords (inherit, initial, unset, revert, revert-layer)
 * before matching against the syntax definition.
 *
 * # Errors
 *
 * Returns a napi error if the syntax string is invalid.
 */
export declare function matchCssProperty(syntax: string, value: string): CssMatchResult

/**
 * Match a CSS value against a CSS Value Definition Syntax string.
 *
 * This is the Rust replacement for css-tree's `lexer.match()`.
 *
 * # Errors
 *
 * Returns a napi error if the syntax string is invalid.
 */
export declare function matchCssSyntax(syntax: string, value: string): CssMatchResult

/** A serializable element node with additional element-specific properties. */
export interface NapiElement {
  /** Internal node ID. */
  id: number
  /** UUID of the element. */
  uuid: string
  /** Raw source text of the opening tag. */
  raw: string
  /** Tag name. */
  nodeName: string
  /** Namespace URI. */
  namespace: string
  /** Whether this is a ghost (omitted) element. */
  isGhost: boolean
  /** Number of attributes. */
  attributeCount: number
  /** Source offset. */
  offset: number
  /** Source line. */
  line: number
  /** Source column. */
  col: number
  /** Nesting depth. */
  depth: number
}

/** A serializable DOM node returned to JS. */
export interface NapiNode {
  /** Internal node ID. */
  id: number
  /** Node type: "document", "element", "text", "comment", "doctype", "psblock", "invalid". */
  nodeType: string
  /** UUID of the node (empty for document). */
  uuid: string
  /** Raw source text. */
  raw: string
  /** Node name (tag name for elements, "#text" for text, etc.). */
  nodeName: string
  /** Source offset. */
  offset: number
  /** Source line (1-based). */
  line: number
  /** Source column (1-based). */
  col: number
  /** Nesting depth. */
  depth: number
}

/** Checks whether a numeric string value falls within an inclusive range. */
export declare function range(value: string, from: number, to: number): boolean

/** Splits a value string into its numeric and unit parts. */
export declare function splitUnit(value: string): SplitUnitResult

/** Splits a value string into its numeric and unit parts. */
export interface SplitUnitResult {
  num: string
  unit: string
}
