/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A DOM tree built from an MLAST JSON string.
 *
 * Use the constructor to parse MLAST JSON and build the DOM.
 * Then query nodes by UUID or traverse the tree.
 */
export declare class NapiDom {
  /**
   * Build a DOM from an MLAST JSON string.
   *
   * # Errors
   *
   * Returns an error if the JSON cannot be parsed as a valid MLAST document.
   */
  constructor(mlastJson: string)
  /**
   * Build a DOM by parsing an HTML string directly (no MLAST JSON).
   *
   * Uses the Rust WHATWG-conformant HTML parser. Automatically detects
   * whether the input is a full document or a fragment.
   */
  static fromHtml(html: string): NapiDom
  /** Total number of nodes in the DOM. */
  get nodeCount(): number
  /** Get a node by its UUID string. Returns null if not found. */
  getNodeByUuid(uuid: string): NapiNode | null
  /** Get a node by its internal ID. Returns null if not found. */
  getNode(id: number): NapiNode | null
  /** Get all element nodes in the DOM. */
  getElements(): Array<NapiElement>
  /** Get the children of a node by its ID. */
  getChildren(id: number): Array<NapiNode>
  /** Get the parent of a node by its ID. Returns null if root. */
  getParent(id: number): NapiNode | null
  /** Get the next sibling of a node. Returns null if last child. */
  getNextSibling(id: number): NapiNode | null
  /** Get the previous sibling of a node. Returns null if first child. */
  getPrevSibling(id: number): NapiNode | null
  /** Get all ancestor nodes of a node (bottom-up, excluding the node itself). */
  getAncestors(id: number): Array<NapiNode>
  /** Get all descendant nodes of a node in document order. */
  getDescendants(id: number): Array<NapiNode>
}

/** A serializable element node with additional element-specific properties. */
export interface NapiElement {
  /** Internal node ID. */
  id: number
  /** UUID of the element. */
  uuid: string
  /** Raw source text of the opening tag. */
  raw: string
  /** Tag name. */
  nodeName: string
  /** Namespace URI. */
  namespace: string
  /** Whether this is a ghost (omitted) element. */
  isGhost: boolean
  /** Number of attributes. */
  attributeCount: number
  /** Source offset. */
  offset: number
  /** Source line. */
  line: number
  /** Source column. */
  col: number
  /** Nesting depth. */
  depth: number
}

/** A serializable DOM node returned to JS. */
export interface NapiNode {
  /** Internal node ID. */
  id: number
  /** Node type: "document", "element", "text", "comment", "doctype", "psblock", "invalid". */
  nodeType: string
  /** UUID of the node (empty for document). */
  uuid: string
  /** Raw source text. */
  raw: string
  /** Node name (tag name for elements, "#text" for text, etc.). */
  nodeName: string
  /** Source offset. */
  offset: number
  /** Source line (1-based). */
  line: number
  /** Source column (1-based). */
  col: number
  /** Nesting depth. */
  depth: number
}
