export { ELEMENT_NODE, TEXT_NODE, SVG_NAMESPACE, XHTML_NAMESPACE } from './dom.js';
export {
	EMBEDDED_CONTROL_ROLES,
	TEXT_INPUT_TYPES,
	TEXT_LIKE_INPUT_TYPES,
	DEFAULT_SUBMIT_LABEL,
	DEFAULT_RESET_LABEL,
	DEFAULT_IMAGE_LABEL,
	isNativeEmbeddedControl,
} from './accname.js';
