/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  gettingStarted: [
    'getting-started',
    'set-up-rules',
    'setting-for-other-languages',
    'cli',
  ],
  rules: [
    {
      "type": "category",
      "label": "Rules",
      link: {
        type: 'doc',
        id: 'rules',
      },
      "items": [
        {
          "type": "autogenerated",
          "dirName": "rules"
        }
      ]
    },
  ],
  configuration: [
    'configuration/index',
    'configuration/regex-selector-sample',
  ],
};

module.exports = sidebars;
