/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
	guide: [
		{
			type: 'category',
			collapsible: false,
			label: 'Guides',
			link: {
				type: 'doc',
				id: 'guides/index',
			},
			items: [
				'guides/ai',
				'guides/beyond-html',
				'guides/applying-rules',
				'guides/selectors',
				'guides/presets',
				'guides/custom-rule',
				'guides/ignoring-code',
				'guides/cli',
				'guides/faq',
			],
		},
	],
	rules: [
		{
			type: 'category',
			collapsible: false,
			collapsed: false,
			label: 'Rules',
			link: {
				type: 'doc',
				id: 'rules/index',
			},
			items: [
				{
					type: 'autogenerated',
					dirName: 'rules',
				},
			],
		},
	],
	configuration: [
		{
			type: 'category',
			collapsible: false,
			collapsed: false,
			label: 'Configuration',
			link: {
				type: 'doc',
				id: 'configuration/index',
			},
			items: [
				'configuration/properties',
				{
					type: 'category',
					collapsible: false,
					collapsed: false,
					label: 'Usecases',
					link: {
						type: 'doc',
						id: 'configuration/usecases/index',
					},
					items: [
						//
						'configuration/usecases/react-project',
						'configuration/usecases/vue-project',
						'configuration/usecases/monorepo',
						'configuration/usecases/ci-cd',
						'configuration/usecases/accessibility',
						'configuration/usecases/architected-css',
						'configuration/usecases/consistent-image-file-naming',
					],
				},
			],
		},
	],
	api: [
		{
			type: 'category',
			label: 'API',
			collapsible: false,
			collapsed: false,
			link: {
				type: 'doc',
				id: 'api/index',
			},
			items: [
				//
				'api/classes',
				'api/types',
				{
					type: 'link',
					label: 'API document',
					href: 'https://api.markuplint.dev',
				},
			],
		},
	],
	migration: [
		{
			type: 'category',
			collapsible: false,
			label: 'Migration',
			link: {
				type: 'doc',
				id: 'migration/index',
			},
			items: [
				{
					type: 'category',
					label: 'v4 to v5',
					collapsible: false,
					link: {
						type: 'doc',
						id: 'migration/v4-to-v5/index',
					},
					items: [
						{
							type: 'category',
							label: 'For Users',
							collapsible: false,
							items: [
								'migration/v4-to-v5/nodejs',
								'migration/v4-to-v5/cli',
								'migration/v4-to-v5/config',
								'migration/v4-to-v5/aria',
								'migration/v4-to-v5/framework',
								{
									type: 'category',
									label: 'Rules',
									collapsed: false,
									items: [
										'migration/v4-to-v5/rules/invalid-attr',
										'migration/v4-to-v5/rules/required-element',
										'migration/v4-to-v5/rules/deprecated-element',
										'migration/v4-to-v5/rules/textlint',
									],
								},
							],
						},
						{
							type: 'category',
							label: 'For Developers',
							collapsible: false,
							items: [
								'migration/v4-to-v5/rule-fix-function',
								'migration/v4-to-v5/api',
								'migration/v4-to-v5/ast',
							],
						},
					],
				},
			],
		},
	],
};

export default sidebars;
