name: Playground Test

on:
    pull_request:
        branches:
            - dev
        paths:
            - 'playground/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
              with:
                  # SEE: https://github.com/lerna/lerna/issues/2542
                  fetch-depth: '0'

            - name: Install Node.js
              uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
              with:
                  node-version: 18

            - name: Cache Restore devDependencies
              id: cache-restore-dev-depends
              uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
              with:
                  path: '**/node_modules'
                  key: dev-depends-ubuntu-latest-node18-${{ hashFiles('yarn.lock') }}

            - name: Playground Building Test
              run: yarn pg:build

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
              with:
                  # SEE: https://github.com/lerna/lerna/issues/2542
                  fetch-depth: '0'

            - name: Install Node.js
              uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
              with:
                  node-version: 18

            - name: Cache Restore devDependencies
              id: cache-restore-dev-depends
              uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
              with:
                  path: '**/node_modules'
                  key: dev-depends-ubuntu-latest-node18-${{ hashFiles('yarn.lock') }}

            - name: Install root dependencies
              run: yarn install --frozen-lockfile

            - name: Playground Lint
              run: yarn pg:lint
