name: Website Test

on:
    pull_request:
        branches:
            - dev
        paths:
            - 'website/**'
            - '.github/workflows/website.yml'

env:
    NODE_BUILD_VERSION: 26

jobs:
    dev-setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

            - name: Use Node.js ${{ env.NODE_BUILD_VERSION }}
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
              with:
                  node-version: ${{ env.NODE_BUILD_VERSION }}

            - name: Enable Corepack and setup Yarn v4
              run: |
                  corepack enable
                  yarn --version

            - name: Cache Restore website dependencies
              id: cache-restore-website
              uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
              with:
                  path: 'website/node_modules'
                  key: website-depends-node${{ env.NODE_BUILD_VERSION }}-${{ hashFiles('website/yarn.lock') }}

            - name: Install website dependencies
              if: steps.cache-restore-website.outputs.cache-hit != 'true'
              run: cd website && yarn install --immutable

            - name: Cache Save website dependencies
              if: steps.cache-restore-website.outputs.cache-hit != 'true'
              uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
              with:
                  path: 'website/node_modules'
                  key: website-depends-node${{ env.NODE_BUILD_VERSION }}-${{ hashFiles('website/yarn.lock') }}

    build:
        needs: dev-setup
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

            - name: Use Node.js ${{ env.NODE_BUILD_VERSION }}
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
              with:
                  node-version: ${{ env.NODE_BUILD_VERSION }}

            - name: Enable Corepack and setup Yarn v4
              run: |
                  corepack enable
                  yarn --version

            - name: Cache Restore website dependencies
              uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
              with:
                  path: 'website/node_modules'
                  key: website-depends-node${{ env.NODE_BUILD_VERSION }}-${{ hashFiles('website/yarn.lock') }}

            - name: Install website dependencies
              run: cd website && yarn install --immutable

            - name: Build
              run: cd website && yarn site:build
