[package]
name = "markuplint-builder"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
markuplint-core = { path = "../markuplint-core" }
markuplint-dom = { path = "../markuplint-dom", features = ["html-parser"] }
markuplint-html-parser = { path = "../markuplint-html-parser" }
markuplint-rules = { path = "../markuplint-rules" }
markuplint-types = { path = "../markuplint-types" }
serde_json = { workspace = true }
napi = { version = "3", features = ["serde-json"] }
napi-derive = "3"

[build-dependencies]
napi-build = "2"

[lints]
workspace = true
